[package]
name = "git-branch-selector"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "gbs"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.2.17", features = ["derive"] }
dialoguer = "0.10.2"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0.32"
toml = "0.5"
