#!/usr/bin/env python3

import os
from typing import Dict

import toml

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(__file__)))


def read_toml(file_path: str) -> Dict:
    with open(file_path, "r") as f:
        return toml.load(f)


if __name__ == "__main__":
    cargo_toml = read_toml(os.path.join(REPO_ROOT, "Cargo.toml"))
    print(cargo_toml["package"]["version"])
