name: git-branch-selector CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  ubuntu:
    name: ubuntu
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Static Analysis
      run: |
        pip install pre-commit
        pre-commit install
        pre-commit run --all-files

    - name: Build & Test
      run: cargo test --release --all-features
