name: git-branch-selector CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  ubuntu:
    name: ubuntu
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Static Analysis
        run: |
          pip install pre-commit
          pre-commit install
          pre-commit run --all-files

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build & Test
        run: |
          # some tests check for colour formatting, so force colours here
          export CLICOLOR_FORCE=1
          cargo test --release --all-features
