name: git-branch-selector CI
permissions: read-all
on:
  pull_request:
  push:
    branches: [main]

jobs:
  ubuntu:
    name: ubuntu
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - uses: taiki-e/install-action@cargo-tarpaulin

      - name: Static Analysis
        run: |
          pip install pre-commit
          pre-commit install
          pre-commit run --all-files

      - name: Run tests
        env:
          CLICOLOR_FORCE: 1
        run: |
          cargo tarpaulin

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
