name: git-branch-selector CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  ubuntu:
    name: ubuntu
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Static Analysis
        run: |
          pip install pre-commit
          pre-commit install
          pre-commit run --all-files

      - uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: stable

      - name: Run cargo-tarpaulin
        uses: actions-rs/tarpaulin@v0.1
        env:
          CLICOLOR_FORCE: 1
        with:
          version: '0.15.0'

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
