name: git-branch-selector release

on:
  workflow_dispatch:

jobs:
  ubuntu:
    name: ubuntu
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get version
        id: get-version
        run: |
          version=$(sed -rn 's/^version\s*=\s*\"([0-9]+.[0-9]+.[0-9]+)\"\s*$/\1/p' Cargo.toml)
          echo ::set-output name=version::${version}

      - name: Make deb package
        run: |
          cargo install cargo-deb
          cargo-deb

      - name: Make release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          deb_rel=$(ls target/debian/*.deb)
          gh release create "${{ steps.get-version.outputs.version }}" \
            ${deb_rel} \
            --target main \
            --title "git-branch-selector: ${{ steps.get-version.outputs.version }}"
